# Generated by Django 3.2.7 on 2021-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jops', '0003_alter_job_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Vacany',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
